/* Source-selected introductions. Published translation/tafsir is never generated here. */
(() => {
 'use strict';
 const D=window.FQ_COMMUNITY,{$,$$,esc:E}=Q,tr=k=>D.labels[Q.lang]?.[k]||D.labels.en[k]||k;
 const P=window.PASSAGES,guideMap=new Map([...D.guides,...D.fullSurahs].map(g=>[g.rank,g]));
 let guideEpoch=0,readingPage=0;
 Q.communityVideos={};
 const chapterNote=s=>({36:'yasin',56:'waqiah',32:'friday',76:'friday',67:'mulk',18:'kahf'}[s]||'general');
 function links(sources){return sources.map(s=>'<a target="_blank" rel="noopener" href="'+E(s.url)+'">'+E(s.label)+'</a>').join(' <span aria-hidden="true"> | </span> ');}
 const section=document.createElement('section');section.className='wrap full-surah-library';section.id='completeSurahs';$('#library').after(section);
 function cards(){section.innerHTML='<div class="section-head"><div><h2>'+E(tr('fullLibrary'))+'</h2><p>'+E(tr('fullIntro'))+'</p></div></div><div class="surah-grid">'+D.fullSurahs.map(s=>'<article class="surah-card"><small>'+E(tr('full'))+' '+s.surahNo+'</small><h3>'+E(s.surah)+'</h3><p lang="'+Q.lang+'">'+E(s.theme[Q.lang])+'</p><span lang="ar" dir="rtl">'+E(s.arabicName)+'</span><div class="control-row"><button type="button" class="btn primary" data-full-surah="'+s.rank+'">'+E(tr('guide'))+'</button><button type="button" class="btn" data-full-listen="'+s.rank+'">'+E(Q.t('listen'))+'</button></div></article>').join('')+'</div>';
 $$('[data-full-surah]',section).forEach(b=>b.onclick=()=>Q.open(+b.dataset.fullSurah));$$('[data-full-listen]',section).forEach(b=>b.onclick=()=>Q.open(+b.dataset.fullListen,'recordings'));
 }
 const btn=document.createElement('button');btn.type='button';btn.className='btn';btn.id='guideTab';$('.study-tabs').prepend(btn);
 const panel=document.createElement('div');panel.id='guidePanel';panel.className='tab-panel';$('.study-main').prepend(panel);
 const baseTab=Q.tab,baseOpen=Q.open,baseLoad=Q.loadAyahs,baseRecordings=Q.recordings;
 Q.tab=name=>{panel.classList.toggle('active',name==='guide');baseTab(name==='guide'?'none':name);btn.setAttribute('aria-selected',String(name==='guide'));};btn.onclick=()=>Q.tab('guide');
 async function sourceQuote(p,n,lang,target,token){const key=D.translationEditions[lang],url='https://quranenc.com/api/v1/translation/aya/'+key+'/'+p.surahNo+'/'+n;try{const [payload,versions]=await Promise.all([Q.json(url),Q.json('https://quranenc.com/api/v1/translations/list/'+lang+'?localization=en').catch(()=>null)]);const row=Q.unbox(payload),editions=Q.unbox(versions),meta=Array.isArray(editions)?editions.find(x=>x.key===key):null;if(token!==guideEpoch||lang!==Q.lang||!target.isConnected)return;if(!row?.translation)throw Error('Missing published translation');target.dataset.sourceReady='true';target.dataset.sourceVersion=meta?.version||'';target.innerHTML='<div class="source-quote" lang="'+lang+'">'+E(Q.plain(row.translation))+'</div><small>QuranEnc | '+E(key)+(meta?.version?' | v'+E(meta.version):'')+' | '+p.surahNo+':'+n+'</small><p><a href="https://quranenc.com/'+lang+'/browse/'+key+'/'+p.surahNo+'/'+n+'" target="_blank" rel="noopener">'+E(tr('source'))+'</a></p>';
 if(row.footnotes){const notes=document.createElement('details');notes.innerHTML='<summary>'+E(Q.t('footnotes'))+'</summary><div lang="'+lang+'">'+E(Q.plain(row.footnotes))+'</div>';target.append(notes);}const more=document.createElement('details');more.innerHTML='<summary>'+E(tr('more'))+'</summary><div class="published-explanation"></div>';target.append(more);let fetched=false;
 more.ontoggle=async()=>{if(!more.open||fetched)return;fetched=true;const out=$('.published-explanation',more);out.textContent=Q.t('loading');try{let text='',publisher='',extra='';if(D.explanationEditions[lang]){const edition=D.explanationEditions[lang],z=Q.unbox(await Q.json('https://quranenc.com/api/v1/translation/aya/'+edition+'/'+p.surahNo+'/'+n));text=Q.plain(z?.translation||'');publisher='Al-Mukhtasar / QuranEnc / '+edition;extra='https://quranenc.com/'+lang+'/browse/'+edition+'/'+p.surahNo+'/'+n;}else{const z=await Q.json('https://alfurqan.online/api/v1/tafseer/ibn-kathir-english/surah/'+p.surahNo+'/ayah/'+n);text=Q.plain(z?.ayah?.text||z?.text||z?.data?.ayah?.text||'');publisher='Ibn Kathir / Al Furqan API';extra='https://quran.com/'+p.surahNo+':'+n+'/tafsirs/en-tafisr-ibn-kathir';}if(!text)throw Error('No published explanation');if(token!==guideEpoch)return;out.innerHTML='<p>'+E(publisher)+'</p><div lang="'+lang+'">'+E(text)+'</div><a href="'+E(extra)+'" target="_blank" rel="noopener">'+E(tr('source'))+'</a>';}catch{fetched=false;out.textContent=tr('unavailable');}};
 }catch{if(token===guideEpoch)target.innerHTML='<p>'+E(tr('unavailable'))+'</p><a href="https://quranenc.com/'+lang+'/browse/'+key+'/'+p.surahNo+'/'+n+'" target="_blank" rel="noopener">'+E(tr('source'))+'</a>';}}
 async function hadith(id,lang,target,token){try{const z=Q.unbox(await Q.json('https://hadeethenc.com/api/v1/hadeeths/one/?id='+id+'&language='+lang));if(token!==guideEpoch||!target.isConnected)return;if(!z?.hadeeth||(lang==='ja'&&!/[\u3040-\u30ff\u4e00-\u9fff]/.test(z.hadeeth))||(lang==='bn'&&!/[\u0980-\u09ff]/.test(z.hadeeth)))throw Error('Published hadith unavailable in selected language');target.innerHTML='<small>'+E(tr('grade'))+': '+E(Q.plain(z.grade)||Q.t('noGrade'))+'</small><p lang="'+lang+'">'+E(Q.plain(z.hadeeth))+'</p><small>'+E(Q.plain(z.attribution||''))+' '+E(Q.plain(z.reference||''))+'</small><details><summary>'+E(tr('more'))+'</summary><p lang="'+lang+'">'+E(Q.plain(z.explanation||''))+'</p></details><a href="https://hadeethenc.com/'+lang+'/browse/hadith/'+id+'" target="_blank" rel="noopener">HadeethEnc '+id+'</a>';}catch{target.innerHTML='<p>'+E(tr('unavailable'))+'</p><a href="https://hadeethenc.com/en/browse/hadith/'+id+'" target="_blank" rel="noopener">'+E(tr('source'))+' (English)</a>';}}
 function showGuide(p){const token=++guideEpoch,lang=Q.lang,g=guideMap.get(p.rank),note=D.practiceNotes[g.note||chapterNote(p.surahNo)],keys=g.keyAyahs;
 panel.innerHTML='<article class="guide-card"><small>'+p.surahNo+':'+E(p.range)+'</small><h2>'+E(g.theme[lang])+'</h2><p class="guide-welcome">'+E(tr('welcome'))+'</p><p class="guide-source-note">'+E(tr('sourceNote'))+'</p><h3>'+E(tr('keyReading'))+'</h3><div data-guide-verse="'+keys[0]+'" class="guide-verse">'+E(Q.t('loading'))+'</div><details class="guide-extra"><summary>'+E(tr('lessons'))+'</summary>'+keys.slice(1).map(n=>'<section class="guide-verse"><h4>'+p.surahNo+':'+n+'</h4><div data-guide-verse="'+n+'">'+E(Q.t('loading'))+'</div></section>').join('')+'</details><div class="control-row"><button type="button" class="btn primary" id="guideRead">'+E(tr('read'))+'</button><button type="button" class="btn" id="guideListen">'+E(tr('media'))+'</button><button type="button" class="btn" id="guideSave">'+E(tr('saveGuide'))+'</button></div><details class="practice-details"><summary>'+E(tr('practice'))+'</summary><small>'+E(tr('editorial'))+'</small><p lang="'+lang+'">'+E(note[lang])+'</p><div class="guide-citations">'+links(note.sources)+'</div></details><details id="guideHadith"><summary>'+E(tr('hadith'))+'</summary><p>'+E(tr(g.hadith?'specificHadith':'generalHadith'))+'</p><div id="guideHadithText"></div></details><p class="guide-source-note">'+E(tr('nativeHelp'))+'</p><button type="button" class="btn" id="guideImport">'+E(tr('import'))+'</button></article>';
 $('#guideRead').onclick=()=>Q.tab('ayahs');$('#guideListen').onclick=()=>Q.tab('recordings');$('#guideImport').onclick=()=>Q.nativeMedia.importer(p.rank);
 const jobs=keys.map(n=>sourceQuote(p,n,lang,$('[data-guide-verse="'+n+'"]',panel),token));
 $('#guideSave').onclick=async()=>{await Promise.all(jobs);if(token!==guideEpoch||!$$('[data-guide-verse]',panel).every(e=>e.dataset.sourceReady==='true')){Q.toast(tr('unavailable'));return;}try{await Q.idb('put','guide:'+p.rank+':'+lang,{rank:p.rank,lang,at:Date.now(),source:'QuranEnc',keyAyahs:keys,contentVersion:D.version});Q.toast(tr('saved'));}catch{Q.toast(Q.t('storageError'));}};
 let hadithLoaded=false;$('#guideHadith').ontoggle=()=>{if($('#guideHadith').open&&!hadithLoaded){hadithLoaded=true;$('#guideHadithText').textContent=Q.t('loading');hadith(g.hadith||10113,lang,$('#guideHadithText'),token);}};
 }
 Q.open=async(rank,tab='guide')=>{const p=P.find(x=>x.rank===+rank);if(!p)return;const pending=baseOpen(+rank,tab);showGuide(p);$('#summary').innerHTML='<p>'+E(guideMap.get(p.rank).theme[Q.lang])+'</p>';Q.tab(tab);await pending;if(Q.active?.rank!==p.rank)return;const group=P.filter(x=>!!x.kind===!!p.kind),i=group.indexOf(p);$('#v3Previous').disabled=i<=0;$('#v3Next').disabled=i>=group.length-1;$('#v3Previous').onclick=()=>{if(group[i-1])Q.open(group[i-1].rank);};$('#v3Next').onclick=()=>{if(group[i+1])Q.open(group[i+1].rank);};};
 function paginate(){const p=Q.active,root=$('#ayahPanel'),rows=$$('.ayah-card',root);if(!p?.kind||rows.length<=20)return;root.querySelector('.reading-pages')?.remove();const total=Math.ceil(rows.length/20);readingPage=Math.min(readingPage,total-1);const nav=document.createElement('div');nav.className='reading-pages';root.prepend(nav);
 function paint(){rows.forEach((r,i)=>r.hidden=Math.floor(i/20)!==readingPage);nav.innerHTML='<button class="btn" data-page-back '+(readingPage===0?'disabled':'')+'>'+E(tr('previous'))+'</button><span>'+E(tr('page'))+' '+(readingPage+1)+' / '+total+'</span><button class="btn" data-page-next '+(readingPage===total-1?'disabled':'')+'>'+E(tr('next'))+'</button>';$('[data-page-back]',nav).onclick=()=>{readingPage--;paint();};$('[data-page-next]',nav).onclick=()=>{readingPage++;paint();nav.scrollIntoView({block:'nearest'});};}paint();Q.revealVerse=n=>{const i=rows.findIndex(r=>r.id==='ayah-'+n);if(i>=0){readingPage=Math.floor(i/20);paint();}};
 }
 Q.loadAyahs=async()=>{readingPage=0;await baseLoad();paginate();};
 const videoLoaded=new Set();
 Q.recordings=async()=>{const p=Q.active;if(!p)return;await baseRecordings();if(Q.active?.rank!==p.rank)return;const root=$('#recordingsPanel');const tools=document.createElement('section');tools.className='guide-card';tools.innerHTML='<h3>'+E(tr('nativeTitle'))+'</h3><p>'+E(tr('importHelp'))+'</p><button type="button" class="btn" id="recordingImport">'+E(tr('import'))+'</button><p>'+E(tr('pendingPublic'))+'</p><h3>'+E(tr('verifiedVideo'))+'</h3><p>'+E(tr('videoContext'))+'</p><button type="button" class="btn" id="additionalVideos">'+E(tr('loadVideo'))+'</button><p id="additionalVideoStatus" role="status"></p>';root.append(tools);$('#recordingImport').onclick=()=>Q.nativeMedia.importer(p.rank);
 const button=$('#additionalVideos');if(videoLoaded.has(p.surahNo))button.hidden=true;
 button.onclick=async()=>{button.disabled=true;const st=$('#additionalVideoStatus');st.textContent=Q.t('loading');try{const z=await Q.json('/api/community-videos?surah='+p.surahNo);if(Q.active?.rank!==p.rank)return;if(!z.videos?.length){st.textContent=tr('unavailable');return;}Q.communityVideos[p.surahNo]=z.videos;videoLoaded.add(p.surahNo);await Q.recordings();}catch{st.textContent=tr('unavailable');}finally{button.disabled=false;}};
 if(p.kind&&!videoLoaded.has(p.surahNo))button.click();
 };
 // A playback queue is independent of the passage currently being browsed.
 const central=$('#ayahPlayer');
 async function playQueued(queue,index){const row=queue.rows[index];if(!row?.audio)return;Q.stop();Q.playQueue=queue;queue.index=index;const full=row.audioMode==='full-surah';Q.currentPlayback={kind:full?'full':'ayah',rank:queue.rank,surah:queue.surah,surahName:queue.surahName,ayah:full?null:row.n,reciterName:queue.reciterName,provider:queue.audioProvider};if(Q.active?.rank===queue.rank){$$('.ayah-card').forEach(e=>e.classList.toggle('is-playing',!full&&e.id==='ayah-'+row.n));}try{await Q.play(central,row.audio);Q.updatePlayback?.();}catch(e){console.warn('Recording play:',e.message);}}
 Q.playAyah=n=>{const r=Q.reading;if(!r)return;const queue={...r,rows:r.rows.map(x=>({...x})),surahName:P.find(x=>x.rank===r.rank)?.surah||'',index:0};return playQueued(queue,queue.rows.findIndex(x=>x.n===+n));};
 Q.playNextAyah=()=>{const q=Q.playQueue;if(q&&Q.currentPlayback?.kind==='ayah'&&q.rows[q.index+1])return playQueued(q,q.index+1);};
 Q.playPreviousAyah=()=>{const q=Q.playQueue;if(q&&Q.currentPlayback?.kind==='ayah'&&q.rows[q.index-1])return playQueued(q,q.index-1);};
 central.onended=()=>{const q=Q.playQueue;if(!q||Q.currentPlayback?.kind!=='ayah')return;if($('#repeatAyah').checked)playQueued(q,q.index);else Q.playNextAyah();};
 Q.stopBrowsing=()=>Q.stopTransient?.();
 window.addEventListener('fq:language',()=>{cards();btn.textContent=tr('guide');});
 document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;const u=$('#utilityDialog'),s=$('#studyDialog');if(u.open)u.close();else if(s.open)s.close();});
 cards();btn.textContent=tr('guide');
})();
