/* Repairs on top of v2; existing notes, hadith favorites and downloads are preserved. */
(()=>{'use strict';
const {$,$$,esc:E}=Q,dialog=$('#studyDialog'),t=k=>window.FQ_V3_TEXT[Q.lang]?.[k]||window.FQ_V3_TEXT.en[k]||k;
const originalStop=Q.stop,originalTab=Q.tab,originalOpen=Q.open;let yt=null,ytTask=null,videoEpoch=0,recordEpoch=0,scanEpoch=0,currentClip=null,currentTab='ayahs';
const clips25=[
 {id:'K1cA-E6MoBU',name:'Qari Ibrahim Idris',range:'25:61-77',note:'mainVideo',views:8153496,metrics:'https://socialcounts.org/youtube-video-live-view-count/K1cA-E6MoBU',checked:'2026-09-22'},
 {id:'z0KNzQCA8d4',name:'Qari Ibrahim Idris',range:'25:61-77',start:800,end:1126,note:'alternate',source:'https://soundcloud.com/reacting-time-685513914/qari-ibrahim-idris-tahajjud-2024'},
 {id:'aN1LfrV_DMk',name:'Muhammad Al-Luhaidan',range:'25:21-77',source:'https://www.youtube.com/watch?v=aN1LfrV_DMk'}
];
const p25=window.PASSAGES.find(p=>p.surahNo===25);if(p25){p25.listen='https://www.youtube.com/watch?v=K1cA-E6MoBU';p25.reciters=[...new Set(['Qari Ibrahim Idris','Mishary Rashid Alafasy','Abdul Rahman Al-Sudais','Abdul Rahman Al-Ossi','Yasser Al-Dosari',...p25.reciters])];}
function theme(){let preference=Q.raw('fqTheme','system');if(!['light','dark','system'].includes(preference))preference='system';document.documentElement.dataset.theme=preference==='system'?(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'):preference;document.querySelector('meta[name="theme-color"]')?.setAttribute('content',document.documentElement.dataset.theme==='light'?'#f4f6f0':'#07130f');const select=$('#themeMode');if(select)select.value=preference;}
const themeControl=document.createElement('label');themeControl.className='theme-control';themeControl.innerHTML='<span id="themeLabel"></span><select id="themeMode"></select>';$('.nav-actions').append(themeControl);$('#themeMode').onchange=e=>{Q.rawSet('fqTheme',e.target.value);theme();};matchMedia('(prefers-color-scheme:dark)').addEventListener('change',theme);
const mushafButton=document.createElement('button');mushafButton.type='button';mushafButton.className='btn';mushafButton.dataset.v3Mushaf='yes';$('.study-tabs').prepend(mushafButton);mushafButton.onclick=()=>Q.tab('mushaf');const scanPanel=document.createElement('div');scanPanel.id='mushafPanel';scanPanel.className='tab-panel';$('.study-main').append(scanPanel);
const nav=document.createElement('div');nav.className='v3-nav';nav.innerHTML='<button class="btn" id="v3Previous"></button><button class="btn" id="v3Next"></button>';$('.dialog-head',dialog).insertBefore(nav,$('[data-close]',dialog));$('#v3Previous').onclick=()=>Q.open(Math.max(1,Q.active.rank-1),currentTab);$('#v3Next').onclick=()=>Q.open(Math.min(30,Q.active.rank+1),currentTab);
$('#mushafLink').onclick=e=>{e.preventDefault();Q.tab('mushaf');};$('#mushafLink').removeAttribute('target');
function labels(){ $('#themeLabel').textContent=t('theme');$('#themeMode').innerHTML=['system','light','dark'].map(x=>`<option value="${x}">${E(t(x))}</option>`).join('');theme();mushafButton.textContent=t('mushaf');$('#mushafLink').textContent=t('mushaf');$('#v3Previous').textContent=t('previous');$('#v3Next').textContent=t('next');}
window.addEventListener('fq:language',labels);labels();
// Only identifiers confirmed by the publisher's verse-by-verse edition catalogue.
$('#ayahReciter').innerHTML='<option value="ar.alafasy">Mishary Rashid Alafasy</option><option value="ar.abdurrahmaansudais">Abdul Rahman Al-Sudais</option><option value="ar.mahermuaiqly">Maher Al-Muaiqly</option><option value="ar.husary">Mahmoud Khalil Al-Husary</option>';
Q.stop=()=>{videoEpoch++;try{yt?.destroy();}catch{}yt=null;originalStop();const slot=$('#v3Player');if(slot&&currentClip)poster(currentClip);};
Q.tab=n=>{currentTab=n;Q.stop();$('#mushafPanel').classList.toggle('active',n==='mushaf');$$('.study-tabs button').forEach(b=>b.setAttribute('aria-selected',b===mushafButton?n==='mushaf':b.dataset.tab===n));if(n==='mushaf'){originalTab('none');renderScans();}else{dialog.classList.remove('wide-reader');originalTab(n);}};
Q.open=async(rank,tab='ayahs')=>{currentClip=null;++recordEpoch;++scanEpoch;const pending=originalOpen(rank,tab);labels();$('#v3Previous').disabled=+rank<=1;$('#v3Next').disabled=+rank>=30;await pending;if(Q.active?.rank!==+rank)return;if(Q.reading?.rows.every(r=>r.arabic&&r.translation))$('#saveReading').disabled=false;};
$('#saveReading').onclick=async()=>{const r=Q.reading;if(!r||!r.rows.every(x=>x.arabic&&x.translation))return;try{await Q.idb('put',`reading:${r.rank}:${r.lang}`,{...r,at:Date.now(),metadataNote:r.meta?null:'Publisher version metadata was unavailable; original source URL and text retained.'});Q.toast(t('readingSaved'));}catch{Q.toast(Q.t('storageError'));}};
function youtubeAPI(){if(window.YT?.Player)return Promise.resolve();if(ytTask)return ytTask;ytTask=new Promise((resolve,reject)=>{const timer=setTimeout(()=>{ytTask=null;reject(Error('YouTube API timeout'));},16000),previous=window.onYouTubeIframeAPIReady;window.onYouTubeIframeAPIReady=()=>{clearTimeout(timer);try{previous?.();}catch{}resolve();};if(!document.querySelector('script[data-fq-youtube]')){const s=document.createElement('script');s.src='https://www.youtube.com/iframe_api';s.dataset.fqYoutube='yes';s.onerror=()=>{clearTimeout(timer);ytTask=null;s.remove();reject(Error('YouTube API unavailable'));};document.head.append(s);}});return ytTask;}
function videoURL(c){return 'https://www.youtube.com/watch?v='+c.id+(c.start?'&t='+c.start+'s':'');}
function poster(c){const slot=$('#v3Player');if(!slot)return;slot.innerHTML=`<img class="v3-poster" alt="" src="https://i.ytimg.com/vi/${E(c.id)}/hqdefault.jpg"><button class="v3-play-poster" type="button" id="v3Start"><span class="v3-play-icon" aria-hidden="true">&#9654;</span><strong>${E(t('watch'))}</strong></button>`;$('#v3Start').onclick=()=>watch(c);}
function choose(c){Q.stop();currentClip=c;$('#v3Title').textContent=c.name+' | '+c.range;$('#v3VideoSource').href=videoURL(c);$('#v3PlayerStatus').textContent=t('notRipped');$('#v3Evidence').innerHTML=c.views?`${E(c.views.toLocaleString(Q.lang))} views | ${E(t('sourceSnapshot'))} | ${E(c.checked)} <a href="${E(c.metrics)}" target="_blank" rel="noopener">SocialCounts</a>`:c.note?E(t(c.note)):c.title?E(c.title):'';poster(c);$$('[data-clip]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.clip===c.id));}
async function watch(c){if(!navigator.onLine){$('#v3PlayerStatus').textContent=t('offlineVideo');return;}Q.stop();currentClip=c;const epoch=videoEpoch,slot=$('#v3Player'),status=$('#v3PlayerStatus');status.classList.remove('v3-error');status.textContent=t('loadingVideo');const frame=document.createElement('iframe');frame.id='fqYouTubeFrame';frame.title=c.name+' '+c.range;frame.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share';frame.allowFullscreen=true;frame.referrerPolicy='strict-origin-when-cross-origin';const params=new URLSearchParams({enablejsapi:'1',origin:location.origin,playsinline:'1',rel:'0',autoplay:'1'});if(c.start)params.set('start',c.start);if(c.end)params.set('end',c.end);frame.src='https://www.youtube-nocookie.com/embed/'+c.id+'?'+params;slot.replaceChildren(frame);
try{await youtubeAPI();if(epoch!==videoEpoch||!frame.isConnected)return;yt=new YT.Player(frame.id,{events:{onReady:()=>{if(epoch===videoEpoch)status.textContent=t('prepared');},onStateChange:e=>{if(epoch===videoEpoch&&e.data===1){document.querySelectorAll('audio,video').forEach(a=>a.pause());status.textContent=t('playing');}},onError:e=>{if(epoch!==videoEpoch)return;const k=e.data===153?'identityError':[101,150].includes(e.data)?'blockedVideo':e.data===100?'notAvailable':'videoFailed';status.textContent=t(k)+' ('+e.data+')';status.classList.add('v3-error');console.warn('Famous Quran YouTube',c.id,e.data);}}});}catch(e){if(epoch===videoEpoch){status.textContent=t('videoFailed');status.classList.add('v3-error');}}}
function clipButtons(clips){return clips.map(c=>`<button class="v3-video-choice" type="button" data-clip="${E(c.id)}" aria-pressed="false"><img src="https://i.ytimg.com/vi/${E(c.id)}/mqdefault.jpg" alt="" loading="lazy"><span><b>${E(c.name)}</b><small>${E(t('range'))}: ${E(c.range)}</small></span></button>`).join('');}
Q.recordings=async()=>{const p=Q.active;if(!p)return;const ticket=++recordEpoch,root=$('#recordingsPanel');let clips=p.surahNo===25?[...clips25]:[];if(!clips.length){try{const id=new URL(p.listen).searchParams.get('v');if(/^[\w-]{11}$/.test(id||''))clips=[{id,name:p.reciters[0],range:p.surahNo+':'+p.range}];}catch{}}
root.innerHTML=`<h3>${E(t('featured'))}</h3>${clips.length?`<div class="video-layout"><section><h4 class="video-selected-title" id="v3Title"></h4><div class="v3-player" id="v3Player"></div><p id="v3PlayerStatus" class="v3-status" role="status"></p><p id="v3Evidence" class="v3-evidence"></p><div class="control-row"><button class="btn" id="v3Retry">${E(t('retry'))}</button><a class="btn" id="v3VideoSource" target="_blank" rel="noopener">${E(t('videoSource'))}</a></div></section><div><div class="v3-video-list" id="v3ClipList">${clipButtons(clips)}</div>${p.surahNo===25?`<button class="btn" id="v3MoreVideos">${E(t('moreVideos'))}</button><p class="v3-status" id="moreVideoStatus"></p>`:''}</div></div>`:`<p class="v3-source-note">${E(t('notAvailable'))}</p><a href="${E(p.listen)}" target="_blank" rel="noopener">${E(t('videoSource'))}</a>`}<h3>${E(t('full'))}</h3><p class="v3-source-note">${E(t('fullHelp'))}</p><div class="v3-audio-grid" id="v3Tracks"><p>${E(t('loading'))}</p></div><p class="v3-source-note">${E(t('downloadHelp'))}</p>`;
function bindClips(){$$('[data-clip]',root).forEach(b=>b.onclick=()=>choose(clips.find(c=>c.id===b.dataset.clip)));}bindClips();if(clips.length){choose(clips[0]);$('#v3Retry').onclick=()=>watch(currentClip);}
if($('#v3MoreVideos'))$('#v3MoreVideos').onclick=async e=>{e.target.disabled=true;const st=$('#moreVideoStatus');st.textContent=t('loading');try{const data=await Q.json('/api/recordings?kind=videos&surah=25');if(ticket!==recordEpoch)return;const extra=(data.videos||[]).filter(c=>/^[\w-]{11}$/.test(c.id)&&!clips.some(x=>x.id===c.id)).map(c=>({...c,range:'25:1-77'}));clips.push(...extra);$('#v3ClipList').innerHTML=clipButtons(clips);bindClips();st.textContent=extra.length?t('verifiedMetadata'):t('notAvailable');}catch{st.textContent=t('catalogFailure');}finally{e.target.disabled=false;}};
async function tracks(){const target=$('#v3Tracks');target.innerHTML=`<p>${E(t('loading'))}</p>`;try{const data=await Q.json('/api/recordings?kind=audio&surah='+p.surahNo);if(ticket!==recordEpoch)return;const items=data.tracks||[];if(!items.length)throw Error('No matching tracks');target.innerHTML=items.map((r,i)=>`<article class="v3-audio-card"><h4>${E(r.name)}</h4><small>${E(p.surah)} | ${E(t('full'))} | MP3Quran</small><audio controls preload="none" id="v3Audio${i}"></audio><div class="control-row"><button class="btn" data-full-play="${i}">${E(t('play'))}</button><button class="btn" data-full-save="${i}">${E(t('save'))}</button><button class="btn" data-full-download="${i}">${E(t('download'))}</button><a class="btn" target="_blank" rel="noopener" href="${E(r.url)}">${E(t('source'))}</a></div><p class="v3-status" id="v3AudioStatus${i}" role="status"></p></article>`).join('');$$('[data-full-play]',target).forEach(b=>b.onclick=()=>{const i=+b.dataset.fullPlay,a=$('#v3Audio'+i);a.onerror=()=>$('#v3AudioStatus'+i).textContent=t('notAvailable');Q.play(a,items[i].url);});async function save(button,i,download){button.disabled=true;const st=$('#v3AudioStatus'+i),r=items[i];st.textContent=t('loading');try{const saved=await Q.saveMedia(r.url,p.surah+' | '+r.name);if(download)Q.download(saved.blob,('Quran-'+p.surahNo+'-'+r.name).replace(/[^a-zA-Z0-9_-]/g,'_')+'.mp3');st.textContent=t('progress')+' | '+(saved.bytes/1048576).toFixed(1)+' MB';}catch(e){st.textContent=t('failed')+': '+e.message;}finally{button.disabled=false;}}$$('[data-full-save]',target).forEach(b=>b.onclick=()=>save(b,+b.dataset.fullSave,false));$$('[data-full-download]',target).forEach(b=>b.onclick=()=>save(b,+b.dataset.fullDownload,true));}catch(e){if(ticket!==recordEpoch)return;target.innerHTML=`<p>${E(t('catalogFailure'))}</p><button class="btn" id="v3RetryTracks">${E(t('retry'))}</button>`;$('#v3RetryTracks').onclick=tracks;}}
tracks();
};
async function renderScans(){const p=Q.active;if(!p)return;const ticket=++scanEpoch;scanPanel.innerHTML=`<div class="mushaf-toolbar"><button class="btn" id="mushafBack">${E(t('back'))}</button><button class="btn" id="mushafWide">${E(t('wide'))}</button><label>${E(t('zoom'))} <input id="mushafZoom" type="range" min="75" max="180" value="100"></label><select class="field" id="mushafJump" aria-label="${E(t('pages'))}"></select><button class="btn" id="mushafSave" disabled>${E(t('saveScans'))}</button></div><p class="mushaf-wide-note">${E(t('context'))}</p><p id="mushafStatus" class="v3-status" role="status">${E(t('loading'))}</p><div id="mushafPages" class="mushaf-pages" tabindex="0" aria-label="${E(t('pages'))}"></div>`;
$('#mushafBack').onclick=()=>Q.tab('ayahs');$('#mushafWide').onclick=()=>dialog.classList.toggle('wide-reader');$('#mushafZoom').oninput=e=>$('#mushafPages').style.setProperty('--scan-width',e.target.value+'%');
let manifests=[];for(const url of p.read){const section=new URL(url).pathname.split('/').pop();try{const z=await Q.json('/api/mushaf?section='+encodeURIComponent(section));manifests.push(z);}catch{if(p.surahNo===25)manifests.push({source:url,images:['p363.gif','p364.gif','p365.gif','p366.gif','p367_1.gif'].map(name=>({name,url:'/api/mushaf?image='+name,original:'https://www.equraninstitute.com/quranreading/quraan_images/'+name}))});}}
if(ticket!==scanEpoch)return;const images=[...new Map(manifests.flatMap(x=>x.images||[]).filter(x=>/^p\d+(?:_[a-zA-Z0-9]+)?\.(gif|png|jpe?g)$/.test(x.name)).map(x=>[x.name,x])).values()];const pages=$('#mushafPages');$('#mushafStatus').textContent=images.length?t('pages')+' | '+images.length:t('scanFailure');if(!images.length){pages.innerHTML=p.read.map(u=>`<a class="btn" href="${E(u)}" target="_blank" rel="noopener">${E(t('scanSource'))}</a>`).join('');return;}
pages.innerHTML=images.map((x,i)=>`<figure class="mushaf-page" id="scanPage${i}"><img src="/api/mushaf?image=${encodeURIComponent(x.name)}" data-original="${E(x.original)}" alt="${E(t('pages'))} ${E(x.name)}" ${i>1?'loading="lazy"':''}><div class="scan-failure" hidden>${E(t('scanFailure'))} <button class="btn" data-scan-retry="${i}">${E(t('retry'))}</button></div><figcaption><a href="${E(x.original)}" target="_blank" rel="noopener">${E(x.name)} | eQuran Institute</a></figcaption></figure>`).join('');$$('.mushaf-page img',pages).forEach(img=>{img.onerror=()=>{if(!img.dataset.triedDirect){img.dataset.triedDirect='1';img.src=img.dataset.original;return;}img.hidden=true;img.nextElementSibling.hidden=false;};});$$('[data-scan-retry]',pages).forEach(b=>b.onclick=()=>{const img=$('img',b.closest('figure'));img.hidden=false;img.nextElementSibling.hidden=true;delete img.dataset.triedDirect;img.src='/api/mushaf?image='+encodeURIComponent(images[+b.dataset.scanRetry].name);});$('#mushafJump').innerHTML=images.map((x,i)=>`<option value="${i}">${E(x.name)}</option>`).join('');$('#mushafJump').onchange=e=>$('#scanPage'+e.target.value).scrollIntoView({block:'start',behavior:'smooth'});$('#mushafSave').disabled=false;$('#mushafSave').onclick=async e=>{e.target.disabled=true;let count=0;try{const cache=await caches.open('fq-original-scans-v1');for(const img of images){const url='/api/mushaf?image='+encodeURIComponent(img.name);if(!await cache.match(url)){const r=await fetch(url);if(!r.ok||!r.headers.get('content-type')?.startsWith('image/'))throw Error(t('scanFailure'));await cache.put(url,r);}$('#mushafStatus').textContent=t('progress')+' '+(++count)+' / '+images.length;}Q.toast(t('savedScans'));}catch(e){$('#mushafStatus').textContent=t('failed')+' '+e.message;}finally{e.target.disabled=false;}};
}
document.addEventListener('play',e=>{if(!(e.target instanceof HTMLMediaElement))return;document.querySelectorAll('audio,video').forEach(a=>{if(a!==e.target)a.pause();});try{yt?.pauseVideo?.();}catch{}},true);
Q.render();
})();
