/* Read-only publisher audit; separate from fixture-based UI tests. */
import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),D=JSON.parse(fs.readFileSync('community-content.json','utf8')),out='verification-artifacts/community-sources';fs.mkdirSync(out,{recursive:true});
const ctx=vm.createContext({window:{}});for(const f of ['passages-1.js','passages-2.js','passages-3.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx);const all=[...ctx.window.PASSAGES,...D.fullSurahs],groups=new Map();for(const p of all){const rows=groups.get(p.surahNo)||[];rows.push(p);groups.set(p.surahNo,rows);}
const report={checkedAt:new Date().toISOString(),scope:'Live publisher text/schema availability, not translation peer review or iPhone playback',translations:[],explanations:[],hadith:[],scans:[],videos:[]};
async function get(url){const r=await fetch(url,{signal:AbortSignal.timeout(18000)});if(!r.ok)throw Error('HTTP '+r.status);const j=await r.json();return j.result??j.data??j;}
async function pool(items,fn,workers=3){const jobs=[...items];await Promise.all(Array.from({length:workers},async()=>{while(jobs.length){const j=jobs.shift();await fn(j);}}));}
const tasks=[...groups].flatMap(([s,ps])=>Object.entries(D.translationEditions).map(([lang,key])=>({s,ps,lang,key})));
await pool(tasks,async({s,ps,lang,key})=>{const url='https://quranenc.com/api/v1/translation/sura/'+key+'/'+s;try{const data=await get(url);assert(Array.isArray(data));const missing=[];for(const p of ps){const g=[...D.guides,...D.fullSurahs].find(x=>x.rank===p.rank);for(const n of g.keyAyahs)if(!data.some(x=>Number(x.aya)===n&&x.translation))missing.push(n);if(p.sections){const end=Number(p.range.match(/\d+/g)[1]);for(let n=1;n<=end;n++)if(!data.some(x=>Number(x.aya)===n&&x.translation))missing.push(n);}}assert(!missing.length,'Missing verses '+missing);fs.writeFileSync(out+'/'+lang+'-'+s+'.json',JSON.stringify(data));report.translations.push({surah:s,lang,key,url,verses:data.length,ok:true});}catch(e){report.translations.push({surah:s,lang,key,url,ok:false,error:e.message});}});
await pool(D.fullSurahs.flatMap(p=>Object.entries(D.explanationEditions).map(([lang,key])=>({p,lang,key}))),async({p,lang,key})=>{const url='https://quranenc.com/api/v1/translation/aya/'+key+'/'+p.surahNo+'/'+p.keyAyahs[0];try{const z=await get(url);assert(z.translation);report.explanations.push({surah:p.surahNo,lang,key,url,ok:true});}catch(e){report.explanations.push({surah:p.surahNo,lang,key,url,ok:false,error:e.message});}});
await pool([10113,6260,6265].flatMap(id=>['en','bn','ja'].map(lang=>({id,lang}))),async({id,lang})=>{const url='https://hadeethenc.com/api/v1/hadeeths/one/?id='+id+'&language='+lang;try{const z=await get(url);assert(z.hadeeth);const match=lang==='en'||(lang==='ja'?/[\u3040-\u30ff\u4e00-\u9fff]/:/[\u0980-\u09ff]/).test(z.hadeeth);assert(match,'Publisher did not supply requested-language text');report.hadith.push({id,lang,url,grade:z.grade,available:true});}catch(e){report.hadith.push({id,lang,url,available:false,error:e.message});}});
const scan=require('../api/mushaf.js'),videos=require('../api/community-videos.js');
function invoke(fn,query){return new Promise((resolve,reject)=>{const res={setHeader(){},status(n){this.code=n;return this;},json(v){resolve({code:this.code||200,value:v});},send(){reject(Error('Expected JSON'));}};Promise.resolve(fn({method:'GET',query},res)).catch(reject);});}
await pool(D.fullSurahs.flatMap(p=>p.sections.map(section=>({surah:p.surahNo,section}))),async({surah,section})=>{try{const z=await invoke(scan,{section});report.scans.push({surah,section,ok:z.code===200&&!!z.value.images?.length,pages:z.value.images?.length,error:z.value.error});}catch(e){report.scans.push({surah,section,ok:false,error:e.message});}});
await pool([19,36,55,56,67],async surah=>{try{const z=await invoke(videos,{surah:String(surah)});report.videos.push({surah,code:z.code,...z.value});}catch(e){report.videos.push({surah,error:e.message});}},2);
fs.writeFileSync('verification-artifacts/community-source-report.json',JSON.stringify(report,null,2));
console.log(JSON.stringify({translations:report.translations.length,translationFailures:report.translations.filter(x=>!x.ok),explanationFailures:report.explanations.filter(x=>!x.ok),unavailableHadith:report.hadith.filter(x=>!x.available),scanFailures:report.scans.filter(x=>!x.ok),videos:report.videos.map(x=>({surah:x.surah,count:x.videos?.length||0}))},null,2));
if(report.translations.some(x=>!x.ok))process.exitCode=1;
