/* Read-only live dependency audit. HTTP success is not proof of playback. */
import fs from 'node:fs';import {createRequire} from 'node:module';const require=createRequire(import.meta.url),mushaf=require('../api/mushaf.js'),recordings=require('../api/recordings.js');fs.mkdirSync('verification-artifacts/live',{recursive:true});const results=[];
async function capture(name,url,kind='json'){try{const r=await fetch(url,{signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('HTTP '+r.status);const body=Buffer.from(await r.arrayBuffer());if(body.length>4000000)throw Error('Large response');fs.writeFileSync('verification-artifacts/live/'+name,body);let value;if(kind==='json')value=JSON.parse(body.toString());results.push({name,url,status:r.status,type:r.headers.get('content-type'),bytes:body.length});return value;}catch(e){results.push({name,url,error:e.message});return null;}}
function response(){return {code:200,setHeader(){},status(c){this.code=c;return this;},json(v){this.value=v;return this;},send(v){this.value=v;return this;}};}
async function route(name,handler,query){const r=response();await handler({method:'GET',query},r);fs.writeFileSync('verification-artifacts/live/'+name,JSON.stringify(r.value,null,2));results.push({name,status:r.code});return r.value;}
const [pages,audioCatalogue,ossiAyah,dosariAyah]=await Promise.all([route('mushaf.json',mushaf,{section:'025_furqan_363_367_j19.htm'}),route('audio-catalogue.json',recordings,{kind:'audio',surah:'25'}),route('ossi-ayah.json',recordings,{kind:'ayah',surah:'25',reciter:'ossi'}),route('dosari-ayah.json',recordings,{kind:'ayah',surah:'25',reciter:'dosari'}),route('video-catalogue.json',recordings,{kind:'videos',surah:'25'}),capture('ibrahim-oembed.json','https://www.youtube.com/oembed?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DK1cA-E6MoBU&format=json'),capture('ibrahim-thumbnail.jpg','https://i.ytimg.com/vi/K1cA-E6MoBU/hqdefault.jpg','binary'),capture('arabic25.json','https://api.alquran.cloud/v1/surah/25/quran-uthmani'),capture('audio25.json','https://api.alquran.cloud/v1/surah/25/ar.alafasy'),capture('translation25.json','https://quranenc.com/api/v1/translation/sura/english_rwwad/25'),capture('metadata.json','https://quranenc.com/api/v1/translations/list/en?localization=en')]);
await Promise.all((pages.images||[]).map(i=>capture(i.name,i.original,'image')));
await Promise.all((audioCatalogue.tracks||[]).map(async track=>{try{const r=await fetch(track.url,{headers:{Range:'bytes=0-4095',Origin:'https://example.org'},signal:AbortSignal.timeout(10000)});results.push({name:track.name,url:track.url,status:r.status,type:r.headers.get('content-type'),cors:r.headers.get('access-control-allow-origin'),scope:'Header/range check, not full playback'});await r.body?.cancel();}catch(e){results.push({name:track.name,error:e.message});}}));
fs.writeFileSync('verification-artifacts/network-audit.json',JSON.stringify({checkedAt:new Date().toISOString(),scope:'Live HTTP and source metadata; not end-to-end playback',results},null,2));console.log(JSON.stringify(results,null,2));

for(const [name,payload] of [['Al-Ossi',ossiAyah],['Al-Dosari',dosariAyah]]){if(!payload?.track?.url||!(payload.timings||[]).length)throw Error(name+' ayah timing route unavailable');results.push({name:name+' ayah timing',timings:payload.timings.length,url:payload.track.url,source:payload.timingSource});}
