/* Public metadata only. Fixed publishers; no YouTube extraction or arbitrary URL requests. */
const wanted=[
 {name:'Mishary Rashid Alafasy',pattern:/mishar[yi]|alafas|al.?afas/i,page:'127'},
 {name:'Abdul Rahman Al-Sudais',pattern:/sudais|sudaes|sudays|sodais/i,page:'66'},
 {name:'Abdul Rahman Al-Ossi',pattern:/al.?ossi|al.?oosi|al.?oussi|aloosi|al.?os[si]+/i},
 {name:'Yasser Al-Dosari',pattern:/^(?=.*yass?[ei]r)(?=.*(?:doss?ar|dawsar)).*$/i,page:'137'},
 {name:'Muhammad Al-Luhaidan',pattern:/luhaidan|lohaidan|luhaiden/i}
];
const cache=new Map();
async function read(url,type='json'){const r=await fetch(url,{signal:AbortSignal.timeout(11000),redirect:'error'});if(!r.ok)throw Error('Source HTTP '+r.status);const text=await r.text();if(text.length>4000000)throw Error('Source response too large');return type==='json'?JSON.parse(text):text;}
function secureMedia(url){try{const u=new URL(url);return u.protocol==='https:'&&/(^|\.)mp3quran\.net$/.test(u.hostname)&&/^\/[a-zA-Z0-9_\/-]*\d{3}\.mp3$/.test(u.pathname)&&!u.search;}catch{return false;}}
const ayahReciters={ossi:'Abdul Rahman Al-Ossi',dosari:'Yasser Al-Dosari'};
module.exports=async function(req,res){res.setHeader('X-Content-Type-Options','nosniff');if(req.method!=='GET')return res.status(405).json({error:'GET only'});const s=Number(req.query.surah),kind=req.query.kind||'audio',reciter=String(req.query.reciter||'');if(!Number.isInteger(s)||s<1||s>114||!['audio','videos','ayah'].includes(kind)||(kind==='ayah'&&!ayahReciters[reciter]))return res.status(400).json({error:'Invalid catalogue request'});const key=kind+':'+s+':'+reciter,old=cache.get(key);if(old&&Date.now()-old.at<3600000){res.setHeader('Cache-Control','public, s-maxage=3600');return res.status(200).json(old.value);}try{let value;
 if(kind==='audio'){const source='https://www.mp3quran.net/api/v3/reciters?language=eng&rewaya=1&sura='+s,z=await read(source),rows=Array.isArray(z.reciters)?z.reciters:[],tracks=[];for(const w of wanted){const r=rows.find(r=>w.pattern.test(r.name||''));if(!r)continue;const m=(r.moshaf||[]).find(m=>String(m.surah_list||'').split(',').map(Number).includes(s));if(!m)continue;const url=String(m.server).replace(/^http:/,'https:').replace(/\/?$/,'/')+String(s).padStart(3,'0')+'.mp3';if(secureMedia(url))tracks.push({name:w.name,publisherName:r.name,edition:m.name,url,reciterId:r.id,scope:'full-surah',source});}value={tracks,source,missing:wanted.filter(w=>!tracks.some(t=>t.name===w.name)).map(w=>w.name),checkedAt:new Date().toISOString()};
 }else if(kind==='ayah'){const wantedName=ayahReciters[reciter],w=wanted.find(x=>x.name===wantedName),source='https://www.mp3quran.net/api/v3/reciters?language=eng&sura='+s,z=await read(source),rows=Array.isArray(z.reciters)?z.reciters:[],r=rows.find(x=>w.pattern.test(x.name||''));if(!r)throw Error('Requested reciter unavailable for this surah');const m=(r.moshaf||[]).find(x=>String(x.surah_list||'').split(',').map(Number).includes(s));if(!m)throw Error('Requested recitation does not include this surah');const url=String(m.server).replace(/^http:/,'https:').replace(/\/?$/,'/')+String(s).padStart(3,'0')+'.mp3';if(!secureMedia(url))throw Error('Publisher media URL rejected');const candidates=[m.id,r.id].filter((x,i,a)=>Number.isInteger(Number(x))&&a.indexOf(x)===i);let timings=[],timingSource='',readId=null;for(const id of candidates){const endpoint='https://mp3quran.net/api/v3/ayat_timing?surah='+s+'&read='+id;try{const t=await read(endpoint);if(Array.isArray(t)&&t.some(x=>Number(x.ayah)>0&&Number.isFinite(Number(x.start_time))&&Number.isFinite(Number(x.end_time)))){timings=t;timingSource=endpoint;readId=Number(id);break;}}catch{}}if(!timings.length)throw Error('Verse timing is not published for this recitation');value={reciter:w.name,publisherName:r.name,track:{url,edition:m.name,reciterId:r.id,readId,scope:'full-surah-with-ayah-timing'},timings:timings.filter(x=>Number(x.ayah)>0).map(x=>({ayah:Number(x.ayah),start_time:Number(x.start_time),end_time:Number(x.end_time)})),source,timingSource,checkedAt:new Date().toISOString()};
 }else{if(s!==25)return res.status(200).json({videos:[],note:'Only independently researched Furqan source pages are resolved here.'});const result=await Promise.allSettled(wanted.filter(w=>w.page).map(async w=>{const source='https://surahquran.com/video-sheikh-'+w.page+'-sora-25-en.html',html=await read(source,'text'),matches=[...html.matchAll(/(?:youtube(?:-nocookie)?\.com\/(?:embed\/|watch\?v=)|youtu\.be\/)([A-Za-z0-9_-]{11})/g)];for(const match of matches.slice(0,3)){const id=match[1],url='https://www.youtube.com/watch?v='+id;try{const m=await read('https://www.youtube.com/oembed?url='+encodeURIComponent(url)+'&format=json');if(!/furq[ae]?[an]+|\u0627\u0644\u0641\u0631\u0642\u0627\u0646/i.test(m.title)||!w.pattern.test(m.title+' '+m.author_name))continue;return{id,name:w.name,title:m.title,author:m.author_name,source,url,scope:/final|verses|excerpt/i.test(m.title)?'excerpt':'source-recording',range:['F1TpygbODzo','h-avYAdweqU'].includes(id)?'25:1-77':null};}catch{}}throw Error('No matching publisher video metadata');}));value={videos:result.filter(x=>x.status==='fulfilled').map(x=>x.value),checkedAt:new Date().toISOString(),unavailable:result.filter(x=>x.status==='rejected').length};}
 cache.set(key,{at:Date.now(),value});res.setHeader('Cache-Control','public, max-age=900, s-maxage=3600, stale-while-revalidate=86400');return res.status(200).json(value);
 }catch(e){res.setHeader('Cache-Control','no-store');return res.status(502).json({error:'Publisher catalogue unavailable',detail:e.message});}};
module.exports.secureMedia=secureMedia;module.exports.wanted=wanted;module.exports.ayahReciters=ayahReciters;
